// Generated by CoffeeScript 1.6.3
(function() {
  window.validate = function(form) {
    var errors, field, name, report, required_field_names, required_fields, _i, _len;
    required_field_names = ['miles', 'gallons'];
    required_fields = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = required_field_names.length; _i < _len; _i++) {
        name = required_field_names[_i];
        _results.push(form.elements[name]);
      }
      return _results;
    })();
    errors = [];
    for (_i = 0, _len = required_fields.length; _i < _len; _i++) {
      field = required_fields[_i];
      if (field.value === '') {
        errors.push(field.name);
      }
    }
    report(errors);
    errors.length === 0;
    report = function(errors) {};
    if (errors.length > 0) {
      return alert("The following fields must be filled out: \n\n " + errors.join("\n "));
    }
  };

  window.math = function(form) {
    var gallons, miles, mpg;
    miles = form.miles.value;
    gallons = form.gallons.value;
    mpg = miles / gallons;
    alert("MPG IS " + mpg);
    return Document.getElementById("result").innerHTML = mpg;
  };

}).call(this);
